### ISSUE TITLE
negative values in vcov_vc(m, sd_cor=F) diagonal

### ISSUE THREAD

**Issue by MonicaFialho** [marklhc/bootmlm#1]
Hi,

I'm conducting a multilevel mediation analysis according to the steps in [this page](https://quantdev.ssri.psu.edu/sites/qdev/files/ILD_Ch07_2017_Within-PersonMedationWithMLM.html), here `vcov_vc` is used to obtain the asymptotic covariances for the random effects.

Using my data (`lme4::lmer` estimated by ML), I get the following results:

```
vcov_vc(m1, sd_cor = FALSE, print_names = FALSE)
              [,1]          [,2]          [,3]          [,4]          [,5]          [,6]         [,7]
[1,]  2.364841e-04 -5.009091e-05 -3.527063e-05 -6.310820e-04 -6.528564e-05 -4.779094e-05 5.988377e-06
[2,] -5.009091e-05 -2.070915e-05 -1.513273e-05 -3.899234e-04 -5.177281e-05 -2.652026e-05 4.091930e-06
[3,] -3.527063e-05 -1.513273e-05  6.970806e-05 -1.931051e-04 -1.953440e-05 -1.780154e-05 2.064570e-06
[4,] -6.310820e-04 -3.899234e-04 -1.931051e-04 -4.075678e-03 -5.564564e-04 -3.346251e-04 4.375257e-05
[5,] -6.528564e-05 -5.177281e-05 -1.953440e-05 -5.564564e-04 -5.040406e-05 -3.466506e-05 5.768651e-06
[6,] -4.779094e-05 -2.652026e-05 -1.780154e-05 -3.346251e-04 -3.466506e-05  6.293230e-05 3.236270e-06
[7,]  5.988377e-06  4.091930e-06  2.064570e-06  4.375257e-05  5.768651e-06  3.236270e-06 3.502431e-06
```

There are some negative values in the diagonal. Shouldn't they all be positive?

Thank you!

**Comment by marklhc** [comment]
Hi,
I'm not sure but maybe looking at your results for `m1` would give some hint. Is there any indication of a singular model or model convergence issue, for example? Sorry, it's hard to pinpoint the reason only based on the information given.
Mark

**Comment by MonicaFialho** [comment]
No, there is no warning associated with the model I'm referring to...

In other models tested I do receive the indication `boundary (singular) fit: see ?isSingular`. Thus that means that the results from `vcov_vc` are not reliable? (as there are no negative values in the diagonal in these cases, I assumed everything was ok)

**Comment by marklhc** [comment]
The `vcov_vc()` really just obtain the Hessian matrix based on the numerical derivatives from the `numDeriv` package. Could you run the following code and see what it shows?

```r
dd2 <- function(vc) {
        sigma <- if (sd_cor) 
            vc[n_th + 1]
        else sqrt(vc[n_th + 1])
        th_sig <- c(to_chol(vc, n = qs, s = sigma), sigma)
        dd(th_sig)
    }
(vc <- lme4::VarCorr(x))
vdd <- as.data.frame(vc, order = "lower.tri")
vc_pars <- vdd[, "vcov"]
(hess <- numDeriv::hessian(dd2, vc_pars))
```

**Comment by MonicaFialho** [comment]
I get `Error in func(x, ...) : object 'sd_cor' not found` when running `(hess <- numDeriv::hessian(dd2, vc_pars))`. The results for the code above that are:

```
> vc
 Groups   Name            Std.Dev. Corr         
 id       sm2:x           0.54640               
          sy:mean_flow_cw 0.32677   0.050       
          x:sy            0.39245  -0.982  0.140
 Residual                 0.16672 

> vdd
       grp            var1            var2         vcov       sdcor
1       id           sm2:x            <NA>  0.298556946  0.54640365
2       id           sm2:x sy:mean_flow_cw  0.009012184  0.05047486
3       id           sm2:x            x:sy -0.210526974 -0.98178210
4       id sy:mean_flow_cw            <NA>  0.106778204  0.32676934
5       id sy:mean_flow_cw            x:sy  0.017980754  0.14021276
6       id            x:sy            <NA>  0.154013254  0.39244522
7 Residual            <NA>            <NA>  0.027795342  0.16671935

> vc_pars
[1]  0.298556946  0.009012184 -0.210526974  0.106778204  0.017980754  0.154013254
[7]  0.027795342
```

**Comment by MonicaFialho** [comment]
I apply your code to some of my other models and I get the same error, so I tried `dd2 <- function(vc, sd_cor=F) {...}`, but then the error was "Error in func(x, ...) : object 'n_th' not found" ...

**Comment by marklhc** [comment]
Sorry a typo in my code. It should be

```
(dd <- devfun_mer(x))
(n_th <- length(x@theta))
(qs <- lengths(x@cnms))
dd2 <- function(vc) {
        sigma <- sqrt(vc[n_th + 1])
        th_sig <- c(to_chol(vc, n = qs, s = sigma), sigma)
        dd(th_sig)
    }
(vc <- lme4::VarCorr(x))
vdd <- as.data.frame(vc, order = "lower.tri")
vc_pars <- vdd[, "vcov"]
(hess <- numDeriv::hessian(dd2, vc_pars))
```

**Comment by MonicaFialho** [comment]
I got the message `Error in to_chol(vc, n = qs, s = sigma) : could not find function "to_chol"` so I added the line `(to_chol <- lme4::Vv_to_Cv)` to your code, bellow `qs`. 

The results I get:

```
> (hess <- numDeriv::hessian(dd2, vc_pars))
            [,1]        [,2]       [,3]         [,4]
[1,]  6470.05135  -3952.4123  1112.5968     48.24782
[2,] -3952.41230 126650.9987 -5906.2080 -10695.82607
[3,]  1112.59684  -5906.2080 26468.7579    136.23714
[4,]    48.24782 -10695.8261   136.2371   1946.14627
[5,] -5633.24439    908.0014 -8465.6900 -10143.95550
[6,]   666.77800  -7751.9756  1911.0074     89.38512
[7,]   958.83004   1551.6903  -128.8020   4646.81318
            [,5]         [,6]       [,7]
[1,]  -5633.2444    666.77800    958.830
[2,]    908.0014  -7751.97562   1551.690
[3,]  -8465.6900   1911.00737   -128.802
[4,] -10143.9555     89.38512   4646.813
[5,]  89753.9735 -10918.98987   2540.546
[6,] -10918.9899  23942.17443   1534.904
[7,]   2540.5460   1534.90391 504004.800
```

Thanks for your time helping me!

**Comment by marklhc** [comment]
Thanks. I couldn't find out what the problem could be. The model setup seems a bit different from the [link](https://quantdev.ssri.psu.edu/sites/qdev/files/ILD_Ch07_2017_Within-PersonMedationWithMLM.html) provided. An alternative is to do the bootstrap. Here's some example syntax:

```r
library(bootmlm)
boo <- bootstrap_mer(m1, FUN = function(x) as.data.frame(VarCorr(x))$vcov, 
                     type = "residual", nsim = 200)
apply(boo$t, 2, sd)  # bootstrap standard error
cov(boo$t)  # bootstrap covariance matrix
```

**Comment by MonicaFialho** [comment]
I tried your code with my model `m1` but I get an error:

```
Warning in .local(x, ...) :
  Cholmod warning 'not positive definite' at file ../Cholesky/t_cholmod_rowfac.c, line 430
Warning in (rsp$y - rsp$mu)/sqrt(1 - hat_e) :
  longer object length is not a multiple of shorter object length
Error in fixed + crossprod(Zt, bstar_new) + estar[sample.int(length(estar),  : 
  length of 2nd arg does not match dimension of first
```

I get the same result even if I try some of my other models (for which `vcov_vc` don't give negative values in the diagonal).

I also tried the function with the model `mediationmodel.lmer` from the [example](https://quantdev.ssri.psu.edu/sites/qdev/files/ILD_Ch07_2017_Within-PersonMedationWithMLM.html), The results are:

```
Warning in .local(x, ...) :
  Cholmod warning 'not positive definite' at file ../Cholesky/t_cholmod_rowfac.c, line 430
200 message(s) : boundary (singular) fit: see ?isSingular

> apply(boo$t, 2, sd)  # bootstrap standard error
[1] 0.018194230 0.010719144 0.005088299 0.009517071
[5] 0.008665860 0.006159915 0.003196279 0.023282954

> cov(boo$t)  # bootstrap covariance matrix
              [,1]          [,2]          [,3]
[1,]  3.310300e-04  3.116542e-05  6.330532e-07
[2,]  3.116542e-05  1.149000e-04 -2.959862e-06
[3,]  6.330532e-07 -2.959862e-06  2.589079e-05
[4,]  7.114987e-05  4.534287e-05  7.702401e-06
[5,] -7.144461e-07  5.968415e-06  1.285049e-05
[6,]  1.466152e-05  2.133879e-05  2.361317e-05
[7,] -6.628423e-07 -4.899262e-07 -2.115830e-08
[8,] -3.404095e-05 -6.473889e-06 -9.844418e-06
              [,4]          [,5]          [,6]
[1,]  7.114987e-05 -7.144461e-07  1.466152e-05
[2,]  4.534287e-05  5.968415e-06  2.133879e-05
[3,]  7.702401e-06  1.285049e-05  2.361317e-05
[4,]  9.057463e-05  1.318918e-05  1.301463e-05
[5,]  1.318918e-05  7.509713e-05  2.608487e-05
[6,]  1.301463e-05  2.608487e-05  3.794455e-05
[7,] -7.151368e-07  4.291489e-06  4.910822e-07
[8,]  3.871176e-06  2.616505e-06 -1.318709e-05
              [,7]          [,8]
[1,] -6.628423e-07 -3.404095e-05
[2,] -4.899262e-07 -6.473889e-06
[3,] -2.115830e-08 -9.844418e-06
[4,] -7.151368e-07  3.871176e-06
[5,]  4.291489e-06  2.616505e-06
[6,]  4.910822e-07 -1.318709e-05
[7,]  1.021620e-05 -5.783700e-06
[8,] -5.783700e-06  5.420960e-04
```

Despite working, `cov(boo$t)` gives different results from those obtained with `vcov_vc(mediationmodel.lmer, sd_cor = FALSE, print_names = TRUE))[2,2]` for that particular model...

------------------------------------------------------------------------------------------------------------------------

Given all the information exposed in this issue, and my inability to understand all the math involved, I guess I could summarize my thoughts as:

When I get negative variances, I know there is something wrong. But for the models that I get positive variances, as supposed, it is valid to assume that these values (while positive) are correct?
[if your answer is no, maybe I'll go for `bmlm:mlm`, despite not allowing for the inclusion of covariates in the model]

Thanks again for your help, and your work :)

**Comment by marklhc** [comment]
Thanks for trying it out! The bootstrap results do not necessarily agree with `vcov_vc()`, which relies on asymptotics, especially in small samples, but I'll have to check how `vcov_vc()` works for this kind of mediation model. In the case they give different results, the bootstrap one should be more accurate. 

I don't know the reason that neither `bootstrap_mer()` nor `vcov_vc()` work for your model; it seems it's different from the one in the example. There's also the built-in bootstrap function from `lme4` that you can try:

```
bootMer(m1, FUN = function(x) as.data.frame(VarCorr(x))$vcov, nsim = 1000)
```
See whether this works. 

Mark

**Comment by MonicaFialho** [comment]
Hi Mark,

`bootMer` runs, but with warnings:

```
Bootstrap Statistics :
        original        bias    std. error
t1*  0.298556946 -0.0109443362 0.098699495
t2*  0.106778204 -0.0032394303 0.059103330
t3*  0.154013254  0.0075355792 0.071957714
t4*  0.009012184 -0.0070755307 0.064912008
t5* -0.210526974  0.0158117641 0.070154066
t6*  0.017980754 -0.0069141016 0.052262410
t7*  0.027795342 -0.0003379232 0.002001997

346 message(s): boundary (singular) fit: see ?isSingular
273 warning(s): Model failed to converge with max|grad| = 0.00201243 (tol = 0.002, component 1) (and others)
```

Should I try another optimizer? If that works, which value of the output should be used as the alternative to `vcov_vc(...)[2,2]`?

---------------------------------

[To clarify what I've been doing]

You have said that my model was different from the example, and it is in fact. Because of some errors/warnings, I've tried different 'combinations' based on the formulation of the example:

```
# Example
mediationmodel.lmer <- lmer(formula = z ~ 0 + 
                                dm + dm:fwkstrcw + dm:timec + 
                                dy + dy:fwkdiscw + dy:fwkstrcw + dy:timec + 
                                (0 + dm:fwkstrcw + dy:fwkdiscw + dy:fwkstrcw | id) + 
                                (0 + dm | timec), 
                  data=datalong) 
```
My models:
A - without `dm`, `dy`, and `(0 + dm | timec)`
B - with `dm` and `dy`, but without `(0 + dm | timec)`
C - with `dm`, `dy`, and `(0 + dm | timec)`
D - without `dm` and `dy`, but with `(0 + dm | timec)`

Regarding the `time` variable, I've tried without it, using it as categorical and as continuous. The `bootMer` warning of model fail occurs in all of them, as well as the warning/error observed using `bootstrap_mer`. Other errors/warnings are still observed, as you can see in the images attached:

`m1` as moderator:
<img width="1228" alt="m1_as_moderator" src="https://user-images.githubusercontent.com/49659181/150239760-bcce0c54-4eb2-4559-adab-5e54d4b4d71c.png">

`m2` as moderator:
<img width="1229" alt="m2_as_moderator" src="https://user-images.githubusercontent.com/49659181/150239766-119d60a7-f82b-4758-ba07-f0e3d84ae87e.png">

Notes: 
- `time1`, `time2`, `time3` and `time4` are 0/1 variables (using `time` as categorical with four levels causes other errors); 
- `timec` are a quantitative variable that represents time in weeks (individuals were measured at different weeks); 
- `assessment` are a factor with four categories

Thank you very much!

**Comment by marklhc** [comment]
Sorry for a late reply. The warning messages shouldn't be a big issue with `bootMer()`, as it is expected that some of the bootstrap samples may not converge given the complexity of the original model. You can use `cov(boo$t)` for the covariance matrix of the estimates, where `boo` is the result from running `bootMer()`.

**Comment by MonicaFialho** [comment]
Hi Mark,

In that case, `cov(boo$t)[2,2]` is the "equivalent" to `vcov_vc(...)[2,2]`?
For the model `m1` with the moderator 2, the later function returns the negative value that motivated this issue:

```
> (varcovajbj=vcov_vc(m1, sd_cor = FALSE, print_names = FALSE)[2,2])
[1] -2.070915e-05
```

while if I use `cov(boo$t)` the result is 

```
> boo <- bootMer(m1, FUN = function(x) as.data.frame(VarCorr(x))$vcov, nsim = 1000, seed=1)
> cov(boo$t)
              [,1]          [,2]          [,3]          [,4]          [,5]
[1,]  1.058495e-02  2.123411e-04  1.835073e-03  5.747999e-04 -4.836184e-03
[2,]  2.123411e-04  3.649322e-03 -1.924991e-04 -5.947227e-06 -9.176005e-05
[3,]  1.835073e-03 -1.924991e-04  4.836481e-03  7.265425e-04 -3.690772e-03
[4,]  5.747999e-04 -5.947227e-06  7.265425e-04  4.136419e-03 -6.869137e-04
[5,] -4.836184e-03 -9.176005e-05 -3.690772e-03 -6.869137e-04  4.504486e-03
[6,] -1.457065e-04 -1.977911e-04 -3.925994e-04 -2.242387e-03  4.820088e-04
[7,] -2.897201e-05 -2.275534e-05 -1.711242e-05  1.842163e-06  1.925520e-05
              [,6]          [,7]
[1,] -1.457065e-04 -2.897201e-05
[2,] -1.977911e-04 -2.275534e-05
[3,] -3.925994e-04 -1.711242e-05
[4,] -2.242387e-03  1.842163e-06
[5,]  4.820088e-04  1.925520e-05
[6,]  2.558111e-03 -4.925701e-06
[7,] -4.925701e-06  4.210506e-06
```

So, `cov(boo$t)[2,2] = 3.649322e-03` is a bootstrapp alternative to `vcov_vc(...)[2,2] = -2.070915e-05`?
[sorry to insist, but since there are no labels, and I don't quite understand the math behind it, I'm afraid of making some mistake]

One last question: I can rely on `cov(boo$t)` approach even for models for which `vcov_vc(...)[2,2]` gives `Error in asMethod(object) : not a positive definite matrix`?

Thank you very much, Mark!

**Comment by marklhc** [comment]
Hi, 

Yes, it is a bootstrap alternative. The `vcov_vc()` function obtains the asymptotic covariance of the random effects by inverting the Hessian, but based on your example, it seems it may run into issues with some unusual models (like mediation using an indicator variable). The bootstrap method is an alternative that resamples the original data with replacement, obtains the estimated random effects in each resample, and then obtains the covariance matrix of those estimates. 

To double-check, I would suggest taking the example from the web page you referenced before, and comparing the two sets of covariances. They won't be exactly the same, but should be relatively close. 

Mark
