### ISSUE TITLE
Residual bootstrap object is S3: boot, parametric is S3: bootMer, boot

### ISSUE THREAD

**Issue by mkshaw** [marklhc/bootmlm#2]
Hi Mark,

Thanks for your great work on this package and the accompanying paper! I'm trying to conduct a simulation study of my own and would like to get confidence intervals for values bootstrapped with the parametric and residual approaches. The parametric bootstrap produces an object of class bootMer and boot, and that works with the `confint()` function in the `stats` package. However, the residual bootstrap produces an object of class boot, which does not work with the `confint()` function. It does work with the `boot.ci` function, but only for one value at a time and my results return 7 values for which I need confidence intervals.

Is there a reason for this difference in classes, and would it be possible for me to conduct residual bootstrapping and get a return value of class bootMer?

Here's some code that replicates my problem, using the example code from the package

```
library(lme4)
fm01ML <- lmer(Yield ~ (1 | Batch), Dyestuff, REML = FALSE)
mySumm <- function(x) {
  c(getME(x, "beta"), sigma(x))
}

# parametric bootstrap
boo_parametric <- bootstrap_mer(fm01ML, mySumm, type = "parametric", nsim = 100)
class(boo_parametric) # returns "bootMer" "boot"
confint(boo_parametric, type = "norm") # returns a confidence interval

# residual bootstrap
boo_resid <- bootstrap_mer(fm01ML, mySumm, type = "residual", nsim = 100)
class(boo_resid) # returns "boot"
confint(boo_resid, type = "norm") # does not work
boot.ci(boo_resid, type = "norm") # kind of works but only for one value at a time
```

Cheers!

**Comment by marklhc** [comment]
Hi @mkshaw, thanks for the question. The difference is because `bootstrap_mer(. . . , type = "parameteric)` simply calls `lme4::bootMer(. . .)`. I was not aware of the `bootMer()` class at the time I wrote `bootstrap_mer()` (or the `lme4:::confint.bootMer()` method might not be available by then). 

One limitation of `lme4:::confint.bootMer()` is that it only supports percentile, basic, and normal CIs, whereas the `boot` package in base R supports also BCa and studentized CIs. If you don't need BCa and studentized CIs, I think you can simply do

```r
class(boo_resid) <- c("boot", "bootMer")
confint(boo_resid, type = "norm")
```

Otherwise, I could create a wrapper similar to `lme4:::confint.bootMer()`, with BCa and studentized CIs. I'll share one in the coming days.

Hope this helps!

**Comment by mkshaw** [comment]
Thank you for your quick response! The `class(boo_resid) <- c("boot", "bootMer")` solution did work for norm/perc/basic CIs, but a wrapper with BCa CIs as well would be fantastic.

**Comment by marklhc** [comment]
I've just added a wrapper that works for BCa in a topic branch. Could you try the following? First, install the topic branch version:

```r
remotes::install_github("marklhc/bootmlm", ref = "confint")
```

and then run

``` r
library(lme4)
#> Loading required package: Matrix
library(bootmlm)
fm01ML <- lmer(Yield ~ (1 | Batch), Dyestuff, REML = FALSE)
mySumm <- function(x) {
  c(getME(x, "beta"), sigma(x))
}

# residual bootstrap
boo_resid <- bootstrap_mer(fm01ML, mySumm, type = "residual", nsim = 100)
#> 10 message(s) : boundary (singular) fit: see help('isSingular')
confint(boo_resid, type = "bca", L = empinf_merm(fm01ML, mySumm))
#>           2.5 %     97.5 %
#> [1,] 1496.63017 1565.49119
#> [2,]   39.32099   64.17293
```

<sup>Created on 2023-05-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Let me know if this works. Thanks!

**Comment by mkshaw** [comment]
It worked! Thanks for your quick work on that.

**Comment by marklhc** [comment]
Great and I've merged the changes to the master branch. Thanks for the suggestion. Will close the issue then.
